Repository GoogleCloudPlatform/compute-image-windows, pull requests merged in 2024-10, with the labels that each got.

#255 Removing logic that checks activation regkey before running ato command
  packaging/googet/google-compute-engine-sysprep.goospec
  sysprep/activate_instance.ps1
Labels: approved, size/XS, lgtm

#257 Remove Microsoft.Copilot package before sysprep.
  packaging/googet/google-compute-engine-sysprep.goospec
  sysprep/sysprep.ps1
Labels: approved, lgtm, size/M

#258 Remove logic that removes Microsoft.Copilot package before sysprep.
  packaging/googet/google-compute-engine-sysprep.goospec
  sysprep/sysprep.ps1
Labels: approved, lgtm, size/S

#259 kms activation to require payg license. metadata.google.internal to ipv4
  packaging/googet/google-compute-engine-powershell.goospec
  packaging/googet/google-compute-engine-sysprep.goospec
  powershell/gce_base.psm1
  sysprep/activate_instance.ps1
  sysprep/instance_setup.ps1
Labels: approved, lgtm, size/L
