Repository GoogleCloudPlatform/compute-image-windows, pull requests merged in 2024-08, with the labels that each got.

#250 Remove mtls mds certs from disk and certstore during sysprep
  packaging/googet/google-compute-engine-sysprep.goospec
  sysprep/sysprep.ps1
Labels: approved, lgtm, size/S

#251 Fix syntax error is goospec release notes
  packaging/googet/google-compute-engine-sysprep.goospec
Labels: approved, size/XS, lgtm

#252 Switch to registry based verification
  sysprep/activate_instance.ps1
Labels: approved, lgtm, size/M

#253 Update exclusion of registry to include Server 2012R2
  sysprep/activate_instance.ps1
Labels: approved, size/XS, lgtm

#254 Update note on using slmgr
  sysprep/activate_instance.ps1
Labels: approved, size/XS, lgtm
