Repository GoogleCloudPlatform/compute-image-windows, pull requests merged in 2024-12, with the labels that each got.

#262 Removing Test-TCPPort
  sysprep/activate_instance.ps1
Labels: approved, lgtm, size/M

#263 Moving initial activation out of loop
  sysprep/activate_instance.ps1
Labels: approved, size/XS, lgtm

#264 Ensure cscript output is written to log also use absolute paths
  sysprep/activate_instance.ps1
Labels: approved, lgtm, size/S

#265 Refactored the script to be sequential and exit if ineligable
  sysprep/activate_instance.ps1
Labels: approved, lgtm, size/L

#266 Remove Pat from owners file.
  OWNERS
Labels: approved, size/XS, lgtm
